.Dd August 03, 2023
.Dt DVD_FB 1
.Sh NAME
.Nm dvd_fb
.Nd dvd screensaver for the linux framebuffer
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/dvd_fb/issues
